# --- Day 13: Transparent Origami --- 

https://adventofcode.com/2021/day/13

## Get Input Data

In [1]:
def parse_data(filename):
    """ """
    transparency = []
    folds = []

    with open (f'../inputs/{filename}') as file:
        for line in file.readlines():
            if line[0].isdigit():
                line = line.strip().split(',')
                transparency.append([int(line[0]), int(line[1])])
            elif line.startswith('fold along '):
                fold = line.strip().split('=')
                folds.append([fold[0][-1], int(fold[1])])

    return transparency, folds

In [2]:
test_transparency, test_folds = parse_data('test_transparency.txt')
test_transparency, test_folds

([[6, 10],
  [0, 14],
  [9, 10],
  [0, 3],
  [10, 4],
  [4, 11],
  [6, 0],
  [6, 12],
  [4, 1],
  [0, 13],
  [10, 12],
  [3, 4],
  [3, 0],
  [8, 4],
  [1, 10],
  [2, 14],
  [8, 10],
  [9, 0]],
 [['y', 7], ['x', 5]])

In [3]:
transparency, folds = parse_data('transparency.txt')

## Part 1
---

## First, do some testing to figure out how `np.flip()` works.

In [4]:
import numpy as np

In [5]:
foo = np.random.randint(2, size=(5, 5))
foo

array([[1, 0, 1, 1, 0],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 0, 1],
       [0, 1, 1, 0, 1],
       [1, 0, 1, 1, 0]])

In [6]:
bar = np.flip(foo, axis=(0))
bar

array([[1, 0, 1, 1, 0],
       [0, 1, 1, 0, 1],
       [1, 1, 1, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 1, 1, 0]])

In [7]:
baz = np.flip(foo, axis=(1))
baz

array([[0, 1, 1, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 1, 1, 1],
       [1, 0, 1, 1, 0],
       [0, 1, 1, 0, 1]])

### Cool. Good to go now.

In [8]:
def make_matrix(dots_data):
    """Read in data for the position of dots on transparency sheet."""

    x_y = list(zip(*dots_data))
    max_x = max(x_y[0]) + 1
    max_y = max(x_y[1]) + 1

    matrix = np.zeros((max_x, max_y), dtype='int')
    matrix[tuple(x_y)] += 1

    # Transpose the matrix because (0, 0) is in the top left corner
    matrix = matrix.T

    return matrix

In [9]:
# Make sure this is producing what I'm expecting!
make_matrix(test_transparency)

array([[0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0]])

In [10]:
def fold_and_count_dots(matrix, folds):
    """Fold the transparency paper (matrix) along the axis and position specified in fold,
    then return the count of positive cells in the new matrix.
    """

    matrix = matrix.copy()

    for i, fold in enumerate(folds):
        
        # Part 1 has just one fold in it
        if i == 0:

            if fold[0] == 'x':
                # Fold left 
                left = matrix[:, :fold[1]]
                right = matrix[:, fold[1]+1:]
                left_flipped = np.flip(left, axis=(1))
                folded_matrix = right + left_flipped

            elif fold[0] == 'y':
                # Fold up
                top = matrix[:fold[1], :]
                bottom = matrix[fold[1]+1:, :]
                bottom_flipped = np.flip(bottom, axis=(0))
                folded_matrix = top + bottom_flipped

        else:
            break
        
    dot_count = np.count_nonzero(folded_matrix)
    return dot_count


### Run on Test Data

In [11]:
fold_and_count_dots(make_matrix(test_transparency), test_folds)  # Should return 17

17

### Run on Input Data

In [12]:
fold_and_count_dots(make_matrix(transparency), folds)

724

## Part 2
---

### Run on Test Data

### Run on Input Data